blueprint:
  name: "Frigate - Telegram Bot (Snapshot + Clip)"
  description: "Notification Frigate avec image snapshot + vidéo clip"
  domain: automation

  input:
    camera:
      name: Caméra Frigate
      selector:
        text:

    config_entry_id:
      name: Telegram config_entry_id
      selector:
        text:

    base_url:
      name: URL externe Home Assistant
      description: "Ex: https://ha.mondomaine.fr"
      selector:
        text:

    notification_text:
      name: Texte personnalisé (optionnel)
      default: ""
      selector:
        text:

    zones:
      name: Zones Frigate (optionnel)
      default: []
      selector:
        select:
          multiple: true
          options: []

    labels:
      name: Objets Frigate (optionnel)
      default: []
      selector:
        select:
          multiple: true
          options:
            - person
            - car
            - dog
            - cat

mode: single
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: frigate/events

variables:
  event_type: "{{ trigger.payload_json.type }}"
  event_id: "{{ trigger.payload_json.after.id }}"
  cam: "{{ trigger.payload_json.after.camera }}"
  label: "{{ trigger.payload_json.after.label | lower }}"
  entered_zones: "{{ trigger.payload_json.after.entered_zones }}"
  base_url: !input base_url
  notif_text: >
    {{ notification_text if notification_text | length > 0
       else '🚨 ' ~ cam | replace('_',' ') | title
       ~ ' : ' ~ label | title ~ ' détecté à '
       ~ states('sensor.time') }}

condition:
  - "{{ event_type == 'new' }}"
  - "{{ cam == !input camera }}"
  - "{{ labels | length == 0 or label in labels }}"
  - "{{ zones | length == 0 or entered_zones | select('in', zones) | list | length > 0 }}"

action:
  # 📸 PHOTO SNAPSHOT
  - service: telegram_bot.send_photo
    data:
      verify_ssl: true
      config_entry_id: !input config_entry_id
      url: "{{ base_url }}/api/frigate/notifications/{{ event_id }}/snapshot.jpg"
      caption: "{{ notif_text }}"
      disable_notification: true

  # 🎬 ATTENTE FIN DE L'ÉVÉNEMENT
  - wait_for_trigger:
      - platform: mqtt
        topic: frigate/events
        value_template: "{{ value_json.after.id }}"
        payload: "{{ event_id }}"
    timeout: "00:02:00"
    continue_on_timeout: false

  # 🎬 ENVOI VIDÉO
  - condition: template
    value_template: "{{ wait.trigger.payload_json.type == 'end' }}"

  - service: telegram_bot.send_video
    data:
      verify_ssl: true
      config_entry_id: !input config_entry_id
      url: "{{ base_url }}/api/frigate/notifications/{{ event_id }}/{{ cam }}/clip.mp4"
      caption: "{{ notif_text }}"
      disable_notification: true
