blueprint:
  name: "Frigate - Telegram Bot (Photo + Clip)"
  description: "Notifications Frigate via telegram_bot.send_photo et send_video"
  domain: automation

  input:
    camera:
      name: "Caméra Frigate"
      description: "Nom de la caméra dans Frigate"

    telegram_target:
      name: "Cible Telegram"
      description: "chat_id ou user_id Telegram"
      selector:
        text:

    notification_text:
      name: "(Optionnel) Texte personnalisé"
      default: ""
      selector:
        text:

    base_url:
      name: "URL externe Home Assistant"
      description: "Obligatoire pour Telegram"
      selector:
        text:

    zone_filter:
      name: "Filtre par zone"
      default: false
      selector:
        boolean: {}

    zones:
      name: "Zones Frigate"
      default: []
      selector:
        object: {}

    labels:
      name: "Objets Frigate"
      default: []
      selector:
        object: {}

    presence_filter:
      name: "Filtre de présence"
      default: ""
      selector:
        entity: {}

mode: single
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: frigate/events
    payload: !input camera
    value_template: "{{ value_json.after.camera }}"

variables:
  id: "{{ trigger.payload_json.after.id }}"
  camera: "{{ trigger.payload_json.after.camera }}"
  camera_name: "{{ camera | replace('_', ' ') | title }}"

  object: "{{ trigger.payload_json.after.label | lower }}"
  label: "{{ trigger.payload_json.after.label | title }}"
  entered_zones: "{{ trigger.payload_json.after.entered_zones }}"

  telegram_target: !input telegram_target
  base_url: !input base_url

  zone_only: !input zone_filter
  zones: !input zones
  labels: "{{ ( !input labels ) | map('lower') | list }}"

  presence_entity: !input presence_filter

  notif_text: >
    {{ notification_text
       if notification_text | length > 0
       else '🚨 Mouvement détecté — Caméra : ' ~ camera_name ~ ' (Objet : ' ~ label ~ ')' }}

condition:
  - "{{ not zone_only or entered_zones | length > 0 }}"
  - "{{ zones | length == 0 or (entered_zones | select('in', zones) | list | length > 0) }}"
  - "{{ labels | length == 0 or object in labels }}"
  - "{{ not presence_entity or not is_state(presence_entity, 'home') }}"

action:
  # 📸 PHOTO
  - action: telegram_bot.send_photo
    data:
      target:
        - "{{ telegram_target }}"
      url: "{{ base_url }}/api/frigate/notifications/{{ id }}/snapshot.jpg"
      caption: "{{ notif_text }}"
      parse_mode: html

  # 🎬 VIDEO (fin de l'événement)
  - repeat:
      sequence:
        - wait_for_trigger:
            - platform: mqtt
              topic: frigate/events
              payload: "{{ id }}"
              value_template: "{{ value_json.after.id }}"
          timeout:
            minutes: 2
          continue_on_timeout: false

        - condition: template
          value_template: "{{ wait.trigger.payload_json.type == 'end' }}"

        - action: telegram_bot.send_video
          data:
            target:
              - "{{ telegram_target }}"
            url: "{{ base_url }}/api/frigate/notifications/{{ id }}/{{ camera }}/clip.mp4"
            caption: "{{ notif_text }}"
            parse_mode: html

      until: "{{ wait.trigger.payload_json.type == 'end' }}"
