blueprint:
  name: Frigate - Notification Telegram
  description: Créez des automatisations pour recevoir des instantanés et des clips depuis Frigate
  domain: automation
  input:
    camera:
      name: Caméra Frigate
      description: Le nom de la caméra tel qu'il est défini dans votre configuration frigate (/conf.yml).
    target_chat:
      name: Cible
      description: 'L’identifiant du chat à utiliser par le bot Telegram. !secret chat_id n’est pas autorisé dans le Blueprint, vous aurez besoin du code chat_id.'
    notification:
      name: Notification
      description: 'Sélectionnez "true" pour désactiver la notification, laissez "false" pour recevoir la notification.'
      selector:
        select:
          options:
          - 'true'
          - 'false'
          sort: false
          custom_value: false
          multiple: false
      default: 'false'
    base_url:
      name: (Facultatif) URL de base
      description: L'URL externe de votre instance Home Assistant. Cela sera par défaut une URL relative et ouvrira les clips dans l'application au lieu du navigateur, ce qui peut poser problème sur certains appareils.
      default: ''
    text:
      name: (Facultatif) Texte de la notification
      description: Texte pour la notification
      default: 'Mouvement détecté, caméra :'
    zone_filter:
      name: (Facultatif) Filtre de zone
      description: Ne notifier que si l'objet est entré dans une zone définie.
      default: false
      selector:
        boolean: {}
    zones:
      name: (Facultatif) Zones de déclenchement
      description: Une liste (-) des zones pour lesquelles vous souhaitez recevoir des notifications.
      default: []
      selector:
        object: {}
    labels:
      name: (Facultatif) Objets de déclenchement
      description: Une liste (-) des objets pour lesquels vous souhaitez recevoir des notifications.
      default: []
      selector:
        object: {}
    presence_filter:
      name: (Facultatif) Filtre de présence
      description: Ne notifier que si l'entité de présence sélectionnée n'est pas "à la maison".
      default: ''
      selector:
        entity:
          multiple: false
mode: single
max_exceeded: silent
trigger:
  platform: mqtt
  topic: frigate/events
  payload: !input camera
  value_template: '{{ value_json[''after''][''camera''] }}'
variables:
  id: '{{ trigger.payload_json[''after''][''id''] }}'
  camera: '{{ trigger.payload_json[''after''][''camera''] }}'
  camera_name: '{{ camera | replace(''_'', '' '') | title }}'
  target_chat: !input target_chat
  object: '{{ trigger.payload_json[''after''][''label''] }}'
  label: '{{ object | title }}'
  entered_zones: '{{ trigger.payload_json[''after''][''entered_zones''] }}'
  type: '{{ trigger.payload_json[''type''] }}'
  base_url: !input base_url
  zone_only: !input zone_filter
  input_zones: !input zones
  zones: '{{ input_zones | list }}'
  input_labels: !input labels
  labels: '{{ input_labels | list }}'
  presence_entity: !input presence_filter
  notification: !input notification
  text: !input text
condition:
- '{{ type != ''end'' }}'
- '{{ not zone_only or entered_zones|length > 0 }}'
- '{{ not zones|length or zones|select(''in'', entered_zones)|list|length > 0 }}'
- '{{ not labels|length or object in labels }}'
- '{{ not presence_entity or not is_state(presence_entity, ''home'') }}'
action:
- service: telegram_bot.send_photo
  data:
    chat_id: '{{ target_chat }}'
    disable_notification: '{{ notification }}'
    caption: '{{ text }} {{ camera_name }} le {{now().strftime("%a %b %d %H:%M:%S %p")}} - (ID: {{ id }})'
    url: '{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg'
- repeat:
    sequence:
    - wait_for_trigger:
      - platform: mqtt
        topic: frigate/events
        payload: '{{ id }}'
        value_template: '{{ value_json[''after''][''id''] }}'
      timeout:
        minutes: 2
      continue_on_timeout: false
    - condition: template
      value_template: '{{ wait.trigger.payload_json[''type''] == ''end'' }}'
    - service: telegram_bot.send_video
      data:
        chat_id: '{{ target_chat }}'
        disable_notification: '{{ notification }}'
        caption: '{{ text }} {{ camera_name }}, le {{now().strftime("%a %b %d %H:%M:%S %p")}}'
        url: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
    until: '{{ wait.trigger.payload_json[''type''] == ''end'' }}'
